"""Initial commit.

Revision ID: 3b5812b6bd90
Revises: 
Create Date: 2020-10-13 06:07:34.296555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5812b6bd90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_list', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_list', type_='foreignkey')
    op.drop_column('user_list', 'user_id')
    # ### end Alembic commands ###
